### ISSUE TITLE
Ошибка 'User': base class undefined

### ISSUE THREAD

**Issue by apbolshakova** [julody/FutuFash#15]
https://github.com/julody/FutuFash/blob/2633dcc6e35ba553809493fbedffd8f1182cf54b/FutuFash/Model.h#L2-L3
Добавить между этими двумя строками class User;

**Comment by apbolshakova** [comment]
Проверить на эту же ошибку другие файлы

**Comment by favoneisss** [comment]
исправлено для классов Model, Designer и User
