### ISSUE TITLE
string без указания пространства имён

### ISSUE THREAD

**Issue by apbolshakova** [julody/FutuFash#17]
https://github.com/julody/FutuFash/blob/719e06c14163dea2ad184aa1300e40e9e4dcd901/FutuFash/Model.h#L10-L18

Спрятать в .cpp файл using namespace это конечно хорошо, но теперь нельзя забывать делать приписку std:: в .h файлах

**Comment by apbolshakova** [comment]
Проверить на эту же ошибку остальные файлы

**Comment by favoneisss** [comment]
исправлено
