### ISSUE TITLE
Доработать printAllProjects

### ISSUE THREAD

**Issue by apbolshakova** [julody/FutuFash#25]
https://github.com/julody/FutuFash/blob/e015fc83dbf03c1575dc3e38c73a5226dad80b5e/FutuFash/ProjectsMenu.cpp#L58-L64

1) Добавить проверку на то, что проект не имеет статус удалён (иначе он удаляется, а в списке всё равно выведется)
2) В конце функции сделать вывод сообщения в духе "Press any button to return" и добавить вызов _getch() (ожидает нажатие любой кнопки)

**Comment by AnastazyaV** [comment]
done
