### ISSUE TITLE
Добавить проверку на то, что проект/пользователь не удалён

### ISSUE THREAD

**Issue by apbolshakova** [julody/FutuFash#35]
Если удалён - не выводить информацию о нём
В функциях вывода вроде printAll

**Comment by favoneisss** [comment]
готово

**Comment by favoneisss** [comment]
хотя нет, не готово

**Comment by favoneisss** [comment]
мне кстати нужен доступ к переменной toDelete которая private, она в Enities.h, поэтому чтобы ничего не сломать(мало ли), я оставлю пока этот вопрос, можем потом вместе это исправить

**Comment by apbolshakova** [comment]
Вопрос с toDelete решён, в главном меню и поиске проверка добавлена

**Comment by AnastazyaV** [comment]
done
