### ISSUE TITLE
wrong output

### ISSUE THREAD

**Issue by AnastazyaV** [julody/FutuFash#37]
![image](https://user-images.githubusercontent.com/43617341/71315043-f1c88000-2464-11ea-86c3-3f35d77a71ab.png)
проверить каждой из нас двоих где эта ошибка появляется, пока я у себя не могу найти, может что-то не так передается в поиске, посмотри плиз)

**Comment by apbolshakova** [comment]
Почему-то было строчка setLocation(name), она перетирала. Исправлено.
