### ISSUE TITLE
Ошибка переопределения базовых типов

### ISSUE THREAD

**Issue by apbolshakova** [julody/FutuFash#4]
https://github.com/julody/FutuFash/blob/6ad0c04cc4e30b34967beac8bb350f64ab5d3099/FutuFash/UserMenu.cpp#L62-L63
Всё-таки нельзя объявить переменную разных типов таким образов (идеи: посмотреть пример с классами персонажей в лекции, задуматься о возможном вынесении создания дизайнера или модели в две разные функции)
@favoneisss

**Comment by favoneisss** [comment]
Исправлено
