### ISSUE TITLE
Отсутствие значений по умолчанию аргументов

### ISSUE THREAD

**Issue by apbolshakova** [julody/FutuFash#5]
https://github.com/julody/FutuFash/blob/6ad0c04cc4e30b34967beac8bb350f64ab5d3099/FutuFash/UserMenu.cpp#L5
Если у какого-то из аргументов есть значение по умолчанию, то у последующих оно тоже должно быть (здесь предполагается что-то в духе UserMenuMode mode = GLOBAL_CHANGING, Project* projectToEdit = nullptr, тогда при вызове из главного меню можно будет передавать только один аргумент - первый)
@favoneisss

**Comment by favoneisss** [comment]
Исправлено
