### ISSUE TITLE
Переход в профиль пользователя после поиска

### ISSUE THREAD

**Issue by apbolshakova** [julody/FutuFash#50]
https://github.com/julody/FutuFash/blob/7d83921e6945528d7524ce7b167a89371098181b/FutuFash/UserMenu.cpp#L366-L368

Здесь нужно забирать именно число строкой, использовать getOperationCode не получится. (проблема: переход в профиль с номером, больше 9-го, т.е. состоящий из двух цифр)

**Comment by favoneisss** [comment]
исправлено
