### ISSUE TITLE
Добавить возможность вводить несколько слов в качестве параметра при создании проекта

### ISSUE THREAD

**Issue by apbolshakova** [julody/FutuFash#54]
https://github.com/julody/FutuFash/blob/7d83921e6945528d7524ce7b167a89371098181b/FutuFash/ProjectsMenu.cpp#L110-L118

Заменить cin на getline. В текущей реализации нельзя, например, создать дизайнера с именем Bolshakova Anzhela

**Comment by AnastazyaV** [comment]
done!)
