### ISSUE TITLE
Добавить возможность вводить несколько слов в качестве параметра при создании и изменении пользователя

### ISSUE THREAD

**Issue by apbolshakova** [julody/FutuFash#55]
https://github.com/julody/FutuFash/blob/7d83921e6945528d7524ce7b167a89371098181b/FutuFash/UserMenu.cpp#L112-L132
Заметить cin >> на getline. Сейчас не возможности вводить параметры из нескольких слов

**Comment by favoneisss** [comment]
исправлено
