### ISSUE TITLE
"using namespace std" в заголовках

### ISSUE THREAD

**Issue by apbolshakova** [julody/FutuFash#7]
В части .h файлов присутствует указанная строка. Перенести в соответствующие .cpp файлы.
Немного документации:
https://docs.microsoft.com/ru-ru/cpp/cpp/namespaces-cpp?view=vs-2019
"Директиву using можно поместить в верхнюю часть CPP-файла (в области видимости файла) или внутрь определения класса или функции.
Без особой необходимости не размещайте директивы using в файлах заголовков (*.h)"

@AnastazyaV 
@favoneisss

**Comment by AnastazyaV** [comment]
Исправлено Настей

**Comment by favoneisss** [comment]
Исправлено
