### ISSUE TITLE
Неправильная реализация handleSearch в ProjectsMenu

### ISSUE THREAD

**Issue by apbolshakova** [julody/FutuFash#8]
https://github.com/julody/FutuFash/blob/6ad0c04cc4e30b34967beac8bb350f64ab5d3099/FutuFash/ProjectsMenu.cpp#L41-L61
Должен просто вызываться конструктор класса поиска. До момента реализации поиска можно оставить тело функции пустым.
@AnastazyaV

**Comment by AnastazyaV** [comment]
Исправлено
